import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Script from "next/script";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <Script
          src="https://cdn.jsdelivr.net/npm/@8thwall/engine-binary@1/dist/xr.js"
          strategy="beforeInteractive"
          crossOrigin="anonymous"
          data-preload-chunks="slam"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/@8thwall/xrextras@1/dist/xrextras.js"
          strategy="beforeInteractive"
          crossOrigin="anonymous"
        />
      </head>
      <body suppressHydrationWarning style={{ fontFamily: 'system-ui, -apple-system, sans-serif' }}>{children}</body>
    </html>
  );
}
