import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Script from "next/script";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning>
      <head>
        <Script
          src="https://cdn.jsdelivr.net/npm/@8thwall/engine-binary@1/dist/xr.js"
          strategy="beforeInteractive"
          crossOrigin="anonymous"
          data-preload-chunks="slam"
        />
      </head>
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
